### ISSUE TITLE
How to use my bitcoin node

### ISSUE THREAD

**Issue by lorenzodisidoro** [btcpayserver/btcpayserver-docker#199]
Hi,

I'm trying to create a custom docker-compose to use my bitcoin node, it is running into a local container with network named `resources_local`, RPC node IP `10.10.0.10` and port `19001` (RPC credentials admin/admin).

I modified the compose as follows but I'm not sure that authentication is correct, I tried to modify `NBXPLORER_BTCRPCURL` passing credentials required by the node like: `http://${BITCOIN_RPC_USER}:${BITCOIN_RPC_PWD}@${BITCOIN_RPCHOST}:${BITCOIN_RPCPORT}` but an error occurred:

```
nbxplorer_1     | info: Configuration:  BTC: Testing RPC connection to http://admin:admin@10.10.0.10:19001/
nbxplorer_1     | fail: Configuration:  BTC: Error connecting to RPC server Connection refused Connection refused
nbxplorer_1     | fail: Configuration:  BTC: Unhandled in Waiter loop
nbxplorer_1     | NBXplorer.Configuration.ConfigException
nbxplorer_1     |    at NBXplorer.Configuration.RPCArgs.TestRPCAsync(NBXplorerNetwork networkInfo, RPCClient rpcClient, CancellationToken cancellation) in /source/NBXplorer/Configuration/RPCArgs.cs:line 132
nbxplorer_1     |    at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 260
nbxplorer_1     |    at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 197
btcpayserver_1  | info: Events:         NBXplorer BTC: NotConnected => Synching
btcpayserver_1  | warn: PayServer:      Error while contacting cryptopia: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. 
```

Here is my compose:
```
version: "3"
services:

  btcpayserver:
    restart: unless-stopped
    image: nicolasdorier/btcpayserver:1.0.2.106
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_EXTERNALURL: ${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST}
      VIRTUAL_HOST_NAME: "btcpay"
      SSL_POLICY: Mozilla-Modern
      LETSENCRYPT_HOST: ${BTCPAY_HOST}
      BTCPAY_CHAINS: "btc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
    links:
    - nbxplorer
    - postgres
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"

  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:1.0.2.31
    expose:
    - "32838"
    networks:
      default:
        ipv4_address: 10.10.0.20
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://${BITCOIN_RPC_USER}:${BITCOIN_RPC_PWD}@${BITCOIN_RPCHOST}:${BITCOIN_RPCPORT}/
      NBXPLORER_BTCNODEENDPOINT: ${BITCOIN_RPCHOST}:${BITCOIN_RPCPORT}
    volumes:
      - "nbxplorer_datadir:/datadir"
      - "bitcoin_datadir:/root/.bitcoin"
    external_links:
      - bitcoin
  postgres:
    restart: unless-stopped
    image: postgres:9.6.5
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"

volumes:
  postgres_datadir: 
  btcpay_datadir: 
  nbxplorer_datadir: 
  bitcoin_datadir: 

networks:
  default:
    external:
      name: resources_local
```

What went wrong?

**Comment by NicolasDorier** [comment]
We removed `cryptopia` long time ago, you run on very old version.
Please check the versions on https://github.com/btcpayserver/btcpayserver-docker/ .

You need to use `NBXPLORER_BTCRPCUSER` and `NBXPLORER_BTCRPCPASSWORD`

**Comment by lorenzodisidoro** [comment]
Oh, I see!

I'm trying to use the latest versions, by changing `nbxplorer` service as a follow
```
nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:2.0.0.19
    expose:
    - "32838"
    networks:
      default:
        ipv4_address: 10.10.0.20
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_NOAUTH: 0
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://10.10.0.10:19001/
      NBXPLORER_BTCRPCUSER: admin
      NBXPLORER_BTCRPCPASSWORD: admin
      NBXPLORER_BTCNODEENDPOINT: 10.10.0.10:19000
    volumes:
      - "nbxplorer_datadir:/datadir"
      - "bitcoin_datadir:/root/.bitcoin"
    external_links:
      - bitcoin
```

and now the error is
```
nbxplorer_1     | info: Configuration:  BTC: Testing RPC connection to http://10.10.0.10:19001/
nbxplorer_1     | fail: Configuration:  BTC: Error connecting to RPC server Connection refused
nbxplorer_1     | fail: Configuration:  BTC: Unhandled in Waiter loop
nbxplorer_1     | NBXplorer.Configuration.ConfigException
nbxplorer_1     |    at NBXplorer.Configuration.RPCArgs.TestRPCAsync(NBXplorerNetwork networkInfo, RPCClient rpcClient, CancellationToken cancellation) in /source/NBXplorer/Configuration/RPCArgs.cs:line 134
nbxplorer_1     |    at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 263
nbxplorer_1     |    at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 200
```

I see you talk about [it here too](https://github.com/dgarage/NBXplorer/issues/172) but I don't think my node container is configured wrong, are other environment variables needed?

**Comment by NicolasDorier** [comment]
you need bitcoind image as well. I advise you against cooking your own docker-compose and instead just use the btcpayserver-docker process which generate it for you, and copy paste what you want to keep.

**Comment by lorenzodisidoro** [comment]
> you need bitcoind image as well. I advise you against cooking your own docker-compose and instead just use the btcpayserver-docker process which generate it for you, and copy paste what you want to keep.

Ok thank you, now it works. I generated `docker-compose` with the `build.sh` script and after that I removed the bitcoind from services and replaced the IP/ports of my local Bitcoin node as a follow
```
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:2.0.0.57
    expose:
      - "32838"
    environment:
      NBXPLORER_NETWORK: regtest
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://10.10.0.10:19001/
      NBXPLORER_BTCRPCUSER: "admin1"
      NBXPLORER_BTCRPCPASSWORD: "admin"
      NBXPLORER_BTCNODEENDPOINT: 10.10.0.10:19000
    volumes:
      - "nbxplorer_datadir:/datadir"
    external_links:
      - bitcoin
```
