### ISSUE TITLE
Integrate ElectrumX Server - how to I make a pull request

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#216]
I made a custom fragment to integrate ElectrumX server to use my BTCPay full bitcoin node.  Thats cool, and works well.  Below is the content of my custom fragment.

I wanted to make a git pull request, but git confuses me, and despite my best attempts to do so watching tutorials etc, I could not work it out.  Anyway, sharing below, as this works well for me.

Content of custom fragment to enable ElectrumX Server to start at same time as BTCPay Server (and use its bitcoin full node):

```
version: "3"

services:
  electrumx:
    image: lukechilds/electrumx
    ports:
      - "50002:50002"
    volumes:
      - /path/to/somedrive/ElectrumX_data:/data
    environment:
      - DAEMON_URL=lnd:afixedpasswordbecauselndsuckswithcookiefile@bitcoind:43782
      - COIN=BitcoinSegwit
```
