### ISSUE TITLE
PiHole needs to be default host for port 80 on Nginx Reverse proxy (if it is enabled)

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/btcpayserver-docker#279]
As per here:
https://github.com/pi-hole/docker-pi-hole#tips-and-tricks

PiHole needs to be default host for port 80 on Nginx Reverse proxy (if it is enabled).  i.e. I think we need to add `DEFAULT_HOST: pi.hole` (as per here: https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose-jwilder-proxy.yml ) in our nginx proxy config.

If you agree @NicolasDorier ill make a PR.  I could not find this implemented so far.

```
services:
  jwilder-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: pi.hole
```
