### ISSUE TITLE
[suggestion] mount an already synched blockchain directory inside the docker

### ISSUE THREAD

**Issue by BobleChinois** [btcpayserver/btcpayserver-docker#34]
I installed BTCPay on a very custom setup and wrote [this article](https://www.sosthene.net/btcpay-bilan/) about my experience so far.
Since I already run a Bitcoin full node on the same machine, I would like to use the already synched blockchain directly with BTCPay.
@NicolasDorier suggested that I use the `docker cp` command to copy the data from my existent node to the volume created inside the docker, but I think it could be even better if I can directly mount the existing .bitcoin directory inside the docker compose. 
What do you think ?

**Comment by Kukks** [comment]
At the end of the generated docker compose file there should be a volumes section described as `volumes:`

You should see `bitcoin_datadir:` or  `litecoin_datadir:` 

You can modify this to: `bitcoin_datadir:/path/to/bitcoin/data` :) 

I am sure you can also try this out with `clightning_litecoin_datadir` and `clightning_bitcoin_datadir` and the other supported lightning stuff.

Just keep in mind that modifying the generated docker compose means that you have to do some steps manually and that the file is overriden every time you run the setup script.

It will be  a good addition if we can specify an existing path through an environment variable though. :)

**Comment by BobleChinois** [comment]
Ok I tried to do that, and failed : 
First I added absolute path to my bitcoin directory to `bitcoin_datadir:` inside `volumes`, resulting in this error when trying to run BTCPay again : 
```
ERROR: yaml.scanner.ScannerError: while scanning a simple key
  in "/home/sosthene/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml", line 162, column 3
could not find expected ':'
  in "/home/sosthene/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml", line 163, column 3
```
Then I read some documentation about volumes and bind mount in docker, and made the following modification in the docker compose file : 
* in `nbexplorer`, `volumes` : `"bitcoin_datadir:/home/sosthene/.bitcoin/testnet3"`
* in `bitcoind`, `volumes` : `"bitcoin_datadir:/home/sosthene/.bitcoin/testnet3"`

I can start btcpay, but it is creating a docker volume and starting the sync all over again.

What do you think ?

**Comment by Kukks** [comment]
Can you share with me both attempts' yml file? 

First version might have been a simple syntax error. Those yml files can be annoying :)

I feel like the second version might be a bad choice as you need that volume configured on a global compose level

**Comment by BobleChinois** [comment]
[docker-compose.generated.yml.txt](https://github.com/btcpayserver/btcpayserver-docker/files/2400711/docker-compose.generated.yml.txt)
Here is the first one

**Comment by Kukks** [comment]
Ok, seems like docker does not support named volumes that bind an existing directory? 

What you could do is replace `bitcoin_datadir` with `/home/sosthene/.bitcoin/testnet3`  and then remove the bitcoin_datadir from volumes at the bottom:

```
version: "3.3"
services:
  nginx:
    restart: unless-stopped
    image: nginx:stable
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    - "lnd_/home/sosthene/.bitcoin/testnet3:/lnd"
    links:
    - btcpayserver
    - "lnd_bitcoin"
  nginx-gen:
    restart: unless-stopped
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    - "lnd_/home/sosthene/.bitcoin/testnet3:/lnd"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    links:
    - nginx
    - "lnd_bitcoin"
  letsencrypt-nginx-proxy-companion:
    restart: unless-stopped
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:rw"
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      ACME_CA_URI: ${ACME_CA_URI:-https://acme-staging.api.letsencrypt.org/directory}
    links:
    - nginx-gen
  btcpayserver:
    restart: unless-stopped
    image: nicolasdorier/btcpayserver:1.0.2.103
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_EXTERNALURL: ${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST}
      SSL_POLICY: Mozilla-Modern
      LETSENCRYPT_HOST: ${BTCPAY_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
      BTCPAY_CHAINS: "btc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_BTCLIGHTNING: "type=lnd-rest;server=http://lnd_bitcoin:8080/;macaroonfilepath=/etc/lnd_bitcoin/admin.macaroon;allowinsecure=true"
      BTCPAY_BTCEXTERNALLNDGRPC: "type=lnd-grpc;server=${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/;macaroonfilepath=/etc/lnd_bitcoin/admin.macaroon"
    links:
    - nbxplorer
    - postgres
    - lnd_bitcoin
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
    - "lnd_/home/sosthene/.bitcoin/testnet3:/etc/lnd_bitcoin"
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:1.0.2.31
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "/home/sosthene/.bitcoin/testnet3:/root/.bitcoin"
    links:
    - bitcoind
  postgres:
    restart: unless-stopped
    image: postgres:9.6.5
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
  bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: nicolasdorier/docker-bitcoin:0.16.3
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NBITCOIN_NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0

        zmqpubrawtx=tcp://0.0.0.0:28332
        zmqpubrawblock=tcp://0.0.0.0:28332
    expose:
    - "43782"
    - "39388"
    - "28332"
    - "28333"
    volumes:
    - "/home/sosthene/.bitcoin/testnet3:/data"
  lnd_bitcoin:
    image: btcpayserver/lnd:0.4.2.0.1
    container_name: btcpayserver_lnd_bitcoin
    restart: unless-stopped
    environment:
      LND_CHAIN: "btc"
      LND_ENVIRONMENT: "${NBITCOIN_NETWORK:-regtest}"
      LND_EXPLORERURL: "http://nbxplorer:32838/"
      LND_EXTRA_ARGS: |
        restlisten=0.0.0.0:8080
        rpclisten=127.0.0.1:10008
        rpclisten=0.0.0.0:10009
        bitcoin.node=bitcoind
        bitcoind.rpchost=bitcoind:43782
        bitcoind.zmqpath=tcp://bitcoind:28332
        externalip=${BTCPAY_HOST}:9730
        alias=${LIGHTNING_ALIAS}
        noencryptwallet=1
        notls=1
    ports:
    - "9730:9735"
    expose:
    - "8080"
    - "9735"
    volumes:
    - "lnd_/home/sosthene/.bitcoin/testnet3:/data"
    - "/home/sosthene/.bitcoin/testnet3:/deps/.bitcoin"
    - "nbxplorer_datadir:/root/.nbxplorer"
    links:
    - nbxplorer
    - bitcoind
volumes:
  nginx_conf: 
  nginx_vhost: 
  nginx_html: 
  nginx_certs: 
  postgres_datadir: 
  btcpay_datadir: 
  nbxplorer_datadir:
  lnd_bitcoin_datadir: 

```

Let me know if that works, curious myself :D

**Comment by BobleChinois** [comment]
Now I got this error : `ERROR: Named volume "lnd_/home/sosthene/.bitcoin/testnet3:/data:rw" is used in service "lnd_bitcoin" but no declaration was found in the volumes section.`

I tried to solve this by erasing the `lnd_` before every occurence of `/home/sosthene...`, but he was doing the resync again.

I found out that docker in fact created a new `testnet3` directory inside the existing one, so I deleted the `/testnet3` and it seemed to work this time !

Here my current docker compose file : 
```
version: "3.3"
services:
  nginx:
    restart: unless-stopped
    image: nginx:stable
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    - "/home/sosthene/.bitcoin:/lnd"
    links:
    - btcpayserver
    - "lnd_bitcoin"
  nginx-gen:
    restart: unless-stopped
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    - "/home/sosthene/.bitcoin:/lnd"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    links:
    - nginx
    - "lnd_bitcoin"
  letsencrypt-nginx-proxy-companion:
    restart: unless-stopped
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:rw"
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      ACME_CA_URI: ${ACME_CA_URI:-https://acme-staging.api.letsencrypt.org/directory}
    links:
    - nginx-gen
  btcpayserver:
    restart: unless-stopped
    image: nicolasdorier/btcpayserver:1.0.2.103
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_EXTERNALURL: ${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST}
      SSL_POLICY: Mozilla-Modern
      LETSENCRYPT_HOST: ${BTCPAY_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
      BTCPAY_CHAINS: "btc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_BTCLIGHTNING: "type=lnd-rest;server=http://lnd_bitcoin:8080/;macaroonfilepath=/etc/lnd_bitcoin/admin.macaroon;allowinsecure=true"
      BTCPAY_BTCEXTERNALLNDGRPC: "type=lnd-grpc;server=${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/;macaroonfilepath=/etc/lnd_bitcoin/admin.macaroon"
    links:
    - nbxplorer
    - postgres
    - lnd_bitcoin
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
    - "/home/sosthene/.bitcoin:/etc/lnd_bitcoin"
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:1.0.2.31
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "/home/sosthene/.bitcoin:/root/.bitcoin"
    links:
    - bitcoind
  postgres:
    restart: unless-stopped
    image: postgres:9.6.5
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
  bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: nicolasdorier/docker-bitcoin:0.16.3
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NBITCOIN_NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0

        zmqpubrawtx=tcp://0.0.0.0:28332
        zmqpubrawblock=tcp://0.0.0.0:28332
    expose:
    - "43782"
    - "39388"
    - "28332"
    - "28333"
    volumes:
    - "/home/sosthene/.bitcoin:/data"
  lnd_bitcoin:
    image: btcpayserver/lnd:0.4.2.0.1
    container_name: btcpayserver_lnd_bitcoin
    restart: unless-stopped
    environment:
      LND_CHAIN: "btc"
      LND_ENVIRONMENT: "${NBITCOIN_NETWORK:-regtest}"
      LND_EXPLORERURL: "http://nbxplorer:32838/"
      LND_EXTRA_ARGS: |
        restlisten=0.0.0.0:8080
        rpclisten=127.0.0.1:10008
        rpclisten=0.0.0.0:10009
        bitcoin.node=bitcoind
        bitcoind.rpchost=bitcoind:43782
        bitcoind.zmqpath=tcp://bitcoind:28332
        externalip=${BTCPAY_HOST}:9730
        alias=${LIGHTNING_ALIAS}
        noencryptwallet=1
        notls=1
    ports:
    - "9730:9735"
    expose:
    - "8080"
    - "9735"
    volumes:
    - "/home/sosthene/.bitcoin:/data"
    - "/home/sosthene/.bitcoin:/deps/.bitcoin"
    - "nbxplorer_datadir:/root/.nbxplorer"
    links:
    - nbxplorer
    - bitcoind
volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  nginx_certs:
  postgres_datadir:
  btcpay_datadir:
  nbxplorer_datadir:
```

**Comment by BobleChinois** [comment]
Ok I'm starting to understand better how it works, I think the file up here would eventually break stuff. Here is the version I'm running now : 
```
version: "3"
services:
  nginx:
    restart: unless-stopped
    image: nginx:stable
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    - "lnd_bitcoin_datadir:/lnd"
    links:
    - btcpayserver
    - "lnd_bitcoin"
  nginx-gen:
    restart: unless-stopped
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    - "lnd_bitcoin_datadir:/lnd"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    links:
    - nginx
    - "lnd_bitcoin"
  letsencrypt-nginx-proxy-companion:
    restart: unless-stopped
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:rw"
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      ACME_CA_URI: ${ACME_CA_URI:-https://acme-staging.api.letsencrypt.org/directory}
    links:
    - nginx-gen
  btcpayserver:
    restart: unless-stopped
    image: nicolasdorier/btcpayserver:1.0.2.103
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_EXTERNALURL: ${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST}
      SSL_POLICY: Mozilla-Modern
      LETSENCRYPT_HOST: ${BTCPAY_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
      BTCPAY_CHAINS: "btc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_BTCLIGHTNING: "type=lnd-rest;server=http://lnd_bitcoin:8080/;macaroonfilepath=/etc/lnd_bitcoin/admin.macaroon;allowinsecure=true"
      BTCPAY_BTCEXTERNALLNDGRPC: "type=lnd-grpc;server=${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/;macaroonfilepath=/etc/lnd_bitcoin/admin.macaroon"
    links:
    - nbxplorer
    - postgres
    - lnd_bitcoin
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
    - "lnd_bitcoin_datadir:/etc/lnd_bitcoin"
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:1.0.2.31
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "/home/sosthene/.bitcoin:/root/.bitcoin"
    links:
    - bitcoind
  postgres:
    restart: unless-stopped
    image: postgres:9.6.5
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
  bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: nicolasdorier/docker-bitcoin:0.16.3
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NBITCOIN_NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0

        zmqpubrawtx=tcp://0.0.0.0:28332
        zmqpubrawblock=tcp://0.0.0.0:28332
    expose:
    - "43782"
    - "39388"
    - "28332"
    - "28333"
    volumes:
    - "/home/sosthene/.bitcoin:/data"
  lnd_bitcoin:
    image: btcpayserver/lnd:0.4.2.0.1
    container_name: btcpayserver_lnd_bitcoin
    restart: unless-stopped
    environment:
      LND_CHAIN: "btc"
      LND_ENVIRONMENT: "${NBITCOIN_NETWORK:-regtest}"
      LND_EXPLORERURL: "http://nbxplorer:32838/"
      LND_EXTRA_ARGS: |
        restlisten=0.0.0.0:8080
        rpclisten=127.0.0.1:10008
        rpclisten=0.0.0.0:10009
        bitcoin.node=bitcoind
        bitcoind.rpchost=bitcoind:43782
        bitcoind.zmqpath=tcp://bitcoind:28332
        externalip=${BTCPAY_HOST}:9730
        alias=${LIGHTNING_ALIAS}
        noencryptwallet=1
        notls=1
    ports:
    - "9730:9735"
    expose:
    - "8080"
    - "9735"
    volumes:
    - "lnd_bitcoin_datadir:/data"
    - "/home/sosthene/.bitcoin:/deps/.bitcoin"
    - "nbxplorer_datadir:/root/.nbxplorer"
    links:
    - nbxplorer
    - bitcoind
volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  nginx_certs:
  postgres_datadir:
  btcpay_datadir:
  nbxplorer_datadir:
  lnd_bitcoin_datadir:
```
