### ISSUE TITLE
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint nginx (ee0b6d6bc2391dfa4d66c1214a2a7c9e64648461ef4220129ca8d56f401005cf9): Bind for 0.0.0.0:443 failed: port is already allocated

### ISSUE THREAD

**Issue by deadcoder0904** [btcpayserver/btcpayserver-docker#858]
i use [coolify](https://coolify.io/) which is a self-hosted heroku to host my [next.js](https://nextjs.org) app.

coolify uses nginx or i think trafaek. at least, i used trafaek when onboarding on coolify.

i tried installing btcpayserver after coolify by running `. ./btcpay-setup.sh -i` but i got this error:

> ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint nginx (ee0b6d6bc2391dfa4d66c1214a2a7c9e64648461ef4220129ca8d56f401005cf9): Bind for 0.0.0.0:443 failed: port is already allocated

how do i fix this?

both are running on the same server (`coolify.example.com` & `btcpay.example.com`). i don't want to use another server.

how do i solve this?

**Comment by ndeet** [comment]
Never needed it myself but imo you need to change the port btcpay nginx is listening to and disable `nginx-https` because you have your own SSL termination and server (traefik). The error is because your nextjs app already takes port 80 and 443 and btcpay can't use it. See also [this guide](https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination) 

Untested but should be something like this:
```
# go into your btcpayserver-docker directory
export REVERSEPROXY_HTTP_PORT=10000
export BTCPAYGEN_EXCLUDE_FRAGMENTS="$BTCPAYGEN_EXCLUDE_FRAGMENTS;nginx-https"
. ./btcpay-setup.sh -i
```

**Comment by deadcoder0904** [comment]
i saw [that guide](https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination) already in the docs but i don't have nginx in folders like that.

like i don't have `/etc/nginx` at all. idk how coolify does it & where it puts nginx/trafaek at all. i tried `whereis` & `which` command but couldn't find their location. i couldn't even find it with `ps -ax | grep nginx` either completely.

i've elaborated [more here on what i actually have here.](https://stackoverflow.com/questions/77685959/error-for-nginx-bind-for-0-0-0-0443-failed-port-is-already-allocated-while-r)

so help me with that. if i'm understanding correctly, what you are saying is i have to follow the guide first, then use your code block which is also in that guide except that `REVERSEPROXY_HTTP_PORT` part so i'll add that in & then map trafaek somehow, in that order right?

**Comment by deadcoder0904** [comment]
bdw i found a `trafaek.conf` on coolify. i can stop it & then edit manually but if i can do it directly then i would love to.

![image](https://github.com/btcpayserver/btcpayserver-docker/assets/16436270/3af70935-ac92-4b1b-9078-c89f9533b386)

```yaml
version: '3.8'
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v2.10'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--providers.docker=true'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.middlewares=traefik-basic-auth@file
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.gzip.compress=true
```

is there anything i can do here?
