### ISSUE TITLE
BTCPay synchronization issue

### ISSUE THREAD

**Issue by blacksocket** [btcpayserver/btcpayserver-docker#990]
Dear All,

I have setup "mynode" server on PROXMOX VM with BTCPay Server >> 1.11.2  alongside existing Bitcoin node and having synching issues below. Seems it is not starting the synchronization. I am bit lost in all these configuration files..

![Image](https://github.com/user-attachments/assets/bb17cf91-a865-405b-bd65-bf2cabe5a231)

root@mynode:/mnt/hdd/mynode/btcpayserver# free -h
.............                                  total        used        free      shared  buff/cache   available
Mem:           7.8Gi       2.7Gi       131Mi        65Mi       5.3Gi       5.1Gi
Swap:          2.0Gi        43Mi       2.0Gi

root@mynode:/mnt/hdd/mynode/btcpayserver# df -h
Filesystem   Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           794M   16M  779M   2% /run
/dev/sda1        32G   11G   19G  37% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
log2ram          40M  7.0M   34M  18% /var/log
/dev/sdb1       1.7T  823G  803G  51% /mnt/hdd
tmpfs           794M   12K  794M   1% /run/user/109
overlay         1.7T  823G  803G  51% /mnt/hdd/mynode/docker/overlay2/462c205c8b3076d13ea32c3bdd99329e9aafd3dc21155e0f641b73526dda517d/merged
tmpfs           794M  8.0K  794M   1% /run/user/1001
overlay         1.7T  823G  803G  51% /mnt/hdd/mynode/docker/overlay2/60db6877d6ed00bd63abe1fcdb17b6ad5c0fbc6a0803bea0a6214e44f0b178d6/merged
overlay         1.7T  823G  803G  51% /mnt/hdd/mynode/docker/overlay2/633fdd97080debe4c04b4c4a2920d684e89634aa1fb45e89e971dad6626894e6/merged
overlay         1.7T  823G  803G  51% /mnt/hdd/mynode/docker/overlay2/6cc2181b63c47d306fb85e4bb2131c3980140b66f12e1282feb76b9b1f3c4660/merged

------------------

_root@mynode:/mnt/hdd/mynode/btcpayserver# docker ps_
CONTAINER ID   IMAGE                              COMMAND                  CREATED             STATUS             PORTS                                             NAMES
0f8f8029e6cf   btcpayserver/btcpayserver:1.11.2   "/app/docker-entrypo…"   43 minutes ago      Up 43 minutes      0.0.0.0:49392->49392/tcp, [::]:49392->49392/tcp   generated_btcpayserver_1

a10990e2449b   nicolasdorier/nbxplorer:2.5.25     "dotnet NBXplorer.dll"   43 minutes ago      Up 43 minutes      32838/tcp                                         generated_nbxplorer_1

514a4632a56c   btcpayserver/postgres:13.18        "/migrate-docker-ent…"   43 minutes ago      Up 43 minutes      5432/tcp                                          generated_postgres_1

----------------------

_root@mynode:/mnt/hdd/mynode/btcpayserver# docker logs -f a10990e2449b_
info: Configuration:  NBXplorer version 2.5.25
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: NBXplorer.DatabaseSetup: Postgres services activated
info: Explorer:       Trimming the event table if needed...
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 0 seconds
System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at NBXplorer.Backend.Indexer.ConnectNode(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 292
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 146
   at NBXplorer.Backend.Indexer.IndexerLoop() in /source/NBXplorer/Backend/Indexer.cs:line 95

----------------------------

_root@mynode:/mnt/hdd/mynode/btcpayserver# docker logs -f 0f8f8029e6cf_
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.11.2
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.11.2
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 1.11.2
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.11.2
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.11.2
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 1.11.2
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: Configuration:  Network: Mainnet
info: Configuration:  LogFile: /datadir/btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Root Path: /
info: Configuration:  Connection to NBXplorer's database successful, dashboard and reporting features activated.
info: PayServer:      Checking if any payment arrived on lightning while the server was offline...
info: PayServer:      Processing lightning payments...
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: PayServer:      Starting payment request expiration watcher
info: PayServer:      0 pending payment requests being checked since last run
info: Configuration:  Now listening on: http://0.0.0.0:49392

----------
Logs from BTCPay GUI below :

2025-05-06 20:57:43.669 +00:00 [INF] Root Path: /
2025-05-06 20:57:44.109 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2025-05-06 20:57:44.150 +00:00 [INF] Checking if any payment arrived on lightning while the server was offline...
2025-05-06 20:57:44.197 +00:00 [INF] Processing lightning payments...
2025-05-06 20:57:44.233 +00:00 [INF] Starting listening NBXplorer (BTC)
2025-05-06 20:57:44.248 +00:00 [INF] Start watching invoices
2025-05-06 21:47:48.771 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2025-05-06 21:47:48.771 +00:00 [INF] TorServices successfully exited...
2025-05-06 21:47:48.772 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2025-05-06 21:47:48.777 +00:00 [INF] PullPaymentHostedService successfully exited...
2025-05-06 21:47:54.737 +00:00 [ERR] BTC: NBXplorer error `Name or service not known (nbxplorer:32838)`
2025-05-06 21:47:54.740 +00:00 [ERR] BTC: NBXplorer error `Name or service not known (nbxplorer:32838)`
2025-05-06 21:48:18.766 +00:00 [INF] NBXplorerListener successfully exited...
2025-05-06 21:48:18.768 +00:00 [INF] LightningListener successfully exited...
2025-05-06 21:48:18.774 +00:00 [INF] LightningPendingPayoutListener successfully exited...
2025-05-06 21:48:18.775 +00:00 [INF] Stop watching invoices
2025-05-06 21:48:18.783 +00:00 [INF] RatesHostedService successfully exited...
2025-05-06 21:48:18.786 +00:00 [INF] DynamicDnsHostedService successfully exited...
2025-05-06 21:48:18.786 +00:00 [INF] DbMigrationsHostedService successfully exited...
2025-05-06 21:51:42.915 +00:00 [INF] Running the migration scripts...
2025-05-06 21:51:43.743 +00:00 [INF] No migrations were applied. The database is already up to date.
2025-05-06 21:51:43.744 +00:00 [INF] All migration scripts ran successfully
2025-05-06 21:51:44.045 +00:00 [INF] Root Path: /
2025-05-06 21:51:44.503 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2025-05-06 21:51:44.544 +00:00 [INF] Checking if any payment arrived on lightning while the server was offline...
2025-05-06 21:51:44.603 +00:00 [INF] Processing lightning payments...
2025-05-06 21:51:44.644 +00:00 [INF] Starting listening NBXplorer (BTC)
2025-05-06 21:51:44.664 +00:00 [INF] Start watching invoices

----

root@mynode:/mnt/hdd/mynode/btcpayserver# docker exec -it a10990e2449b bash

root@a10990e2449b:/app# env
HOSTNAME=a10990e2449b
NBXPLORER_BIND=0.0.0.0:32838
DOTNET_VERSION=8.0.11
APP_UID=1654
PWD=/app
NBXPLORER_BTCRPCUSER=mynode
HOME=/root
NBXPLORER_BTCRPCPASSWORD=password
ASPNETCORE_HTTP_PORTS=8080
NBXPLORER_POSTGRES=User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorermainnet
TERM=xterm
SHLVL=1
ASPNET_VERSION=8.0.11
DOTNET_RUNNING_IN_CONTAINER=true
NBXPLORER_DATADIR=/datadir
NBXPLORER_TRIMEVENTS=10000
NBXPLORER_BTCNODEENDPOINT=host.docker.internal:8333
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NBXPLORER_SIGNALFILESDIR=/datadir
NBXPLORER_CHAINS=btc
NBXPLORER_NETWORK=mainnet
NBXPLORER_BTCRPCURL=http://host.docker.internal:8332/
_=/usr/bin/env

Could you please help with this issue ? 

Many Thanks for All the support!

**Comment by blacksocket** [comment]
root@mynode:/mnt/hdd/mynode/btcpayserver/btcpayserver-docker/Production# cat docker-compose.btc.yml
```
services:
  nginx:
    restart: unless-stopped
    image: nginx:stable
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    links:
    - btcpayserver
  nginx-gen:
    restart: unless-stopped
    image: btcpayserver/docker-gen:0.7.5
    container_name: nginx-gen
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:ro"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    links:
    - nginx
  letsencrypt-nginx-proxy-companion:
    restart: unless-stopped
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "nginx_conf:/etc/nginx/conf.d"
    - "nginx_vhost:/etc/nginx/vhost.d"
    - "nginx_html:/usr/share/nginx/html"
    - "nginx_certs:/etc/nginx/certs:rw"
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      ACME_CA_URI: ${ACME_CA_URI:-staging}
    links:
    - nginx-gen
  btcpayserver:
    restart: unless-stopped
    image: nicolasdorier/btcpayserver:1.0.2.106
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_EXTERNALURL: ${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST}
      VIRTUAL_HOST_NAME: "btcpay"
      SSL_POLICY: Mozilla-Modern
      LETSENCRYPT_HOST: ${BTCPAY_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
      BTCPAY_CHAINS: "btc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
    links:
    - nbxplorer
    - postgres
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:1.0.2.31
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "bitcoin_datadir:/root/.bitcoin"
    links:
    - bitcoind
  postgres:
    restart: unless-stopped
    image: postgres:9.6.5
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
  bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: nicolasdorier/docker-bitcoin:0.16.3
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NBITCOIN_NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
    expose:
    - "43782"
    - "39388"
    - "28332"
    - "28333"
    volumes:
    - "bitcoin_datadir:/data"
volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  nginx_certs:
  postgres_datadir:
  btcpay_datadir:
  nbxplorer_datadir:
  bitcoin_datadir:``
```
